const Dairy = [
  { productId: "dairy_1", name: "Saras Toned Milk", quantity: "500 ml", price: 27, mrp: null, discount: null, image: "dairy/1001.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_2", name: "Saras Gold Full Cream Milk", quantity: "500 ml", price: 34, mrp: null, discount: null, image: "dairy/1002.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_3", name: "Saras Cup Curd", quantity: "200 g", price: 16, mrp: null, discount: null, image: "dairy/1003.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_4", name: "Amul Taaza Toned Milk", quantity: "500 ml", price: 27, mrp: null, discount: null, image: "dairy/1004.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_5", name: "Amul Gold Full Cream Milk", quantity: "500 ml", price: 34, mrp: null, discount: null, image: "dairy/1005.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_6", name: "Amul Salted Butter", quantity: "100 g", price: 58, mrp: null, discount: null, image: "dairy/1006.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_7", name: "Amul Masti Pouch Curd", quantity: "1 kg", price: 77, mrp: null, discount: null, image: "dairy/1007.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_8", name: "Amul Masti Pouch Curd", quantity: "390 g", price: 35, mrp: null, discount: null, image: "dairy/1008.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_9", name: "Harvest Gold Hearty Brown Bread", quantity: "400 g", price: 55, mrp: null, discount: 24, image: "dairy/1009.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_10", name: "Nature Good White Eggs (6 pieces)", quantity: "6 pieces", price: 68, mrp: 90, discount: null, image: "dairy/1010.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_11", name: "Amul Masti Cup Curd", quantity: "200 g", price: 24, mrp: null, discount: null, image: "dairy/1011.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_12", name: "English Oven Premium White Bread 350 g", quantity: "350 g", price: 30, mrp: null, discount: null, image: "dairy/1012.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_13", name: "English Oven Zero Maida Multigrain Bread", quantity: "400 g", price: 70, mrp: null, discount: null, image: "dairy/1013.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_14", name: "Amul Cheese Slices", quantity: "200 g", price: 140, mrp: null, discount: null, image: "dairy/1014.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_15", name: "English Oven Zero maida 100% Atta/ Wheat Bread", quantity: "400 g", price: 55, mrp: null, discount: null, image: "dairy/1015.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_16", name: "Harvest Gold Sandwich White Bread", quantity: "450 g", price: 45, mrp: null, discount: null, image: "dairy/1016.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_17", name: "Britannia Sandwich White Bread", quantity: "600 g", price: 55, mrp: null, discount: null, image: "dairy/1017.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_18", name: "Amul Cheese Cubes", quantity: "200 g", price: 130, mrp: null, discount: null, image: "dairy/1018.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_19", name: "Mother Dairy Classic Cup Curd", quantity: "400 g", price: 50, mrp: null, discount: null, image: "dairy/1019.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_20", name: "Amul Blend Diced Cheese", quantity: "200 g", price: 120, mrp: null, discount: null, image: "dairy/1020.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_21", name: "The Health Factory Zero Maida Whole Wheat Bread", quantity: "250 g", price: 54, mrp: 55, discount: null, image: "dairy/1021.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_22", name: "Amul Salted Butter (200 g)", quantity: "200 g", price: 118, mrp: null, discount: null, image: "dairy/1022.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_23", name: "English Oven Brown Bread", quantity: "400 g", price: 55, mrp: null, discount: null, image: "dairy/1023.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_24", name: "English Oven Zero Maida 100% Whole Wheat Bread", quantity: "400 g", price: 55, mrp: null, discount: null, image: "dairy/1024.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_25", name: "Amul Lactose Free Milk", quantity: "250 ml", price: 25, mrp: null, discount: null, image: "dairy/1025.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_26", name: "English Oven Sandwich White Bread", quantity: "400 g", price: 40, mrp: null, discount: null, image: "dairy/1026.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_27", name: "Farm Made Free Range Eggs", quantity: "6 pieces", price: 143, mrp: 149, discount: null, image: "dairy/1027.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_28", name: "Amul Masti Cup Cup Curd", quantity: "400 g", price: 47, mrp: null, discount: null, image: "dairy/1028.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_29", name: "English Oven Milk Bread", quantity: "400 g", price: 50, mrp: null, discount: 14, image: "dairy/1029.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_30", name: "The Natural Fresh White Protein Rich Eggs - 10 pieces", quantity: "10 pieces", price: 132, mrp: 155, discount: null, image: "dairy/1030.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_31", name: "Mother Dairy Classic Pouch Curd", quantity: "1 kg", price: 77, mrp: null, discount: null, image: "dairy/1031.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_32", name: "Amul Salted Butter (Chiplets)", quantity: "100 g", price: 70, mrp: null, discount: null, image: "dairy/1032.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_33", name: "English Oven Pav", quantity: "250 g", price: 40, mrp: null, discount: null, image: "dairy/1033.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_34", name: "Britannia Brown Bread", quantity: "400 g", price: 55, mrp: null, discount: null, image: "dairy/1034.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_35", name: "Harvest Gold Sweet Bun", quantity: "150 g", price: 20, mrp: null, discount: null, image: "dairy/1035.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_36", name: "Kalory White Pav", quantity: "300 g", price: 39, mrp: 40, discount: null, image: "dairy/1036.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_37", name: "Amul Taaza Homogenised Toned Milk", quantity: "1 l", price: 75, mrp: null, discount: 7, image: "dairy/1037.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_38", name: "FruBon Pasteurized Double Toned Pouch Curd", quantity: "1 kg", price: 71, mrp: 77, discount: 14, image: "dairy/1038.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_39", name: "Nature Good White Eggs (30 pieces)", quantity: "30 pieces", price: 316, mrp: 370, discount: null, image: "dairy/1039.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_40", name: "English Oven Zero Maida Pav", quantity: "250 g", price: 50, mrp: null, discount: 15, image: "dairy/1040.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_41", name: "Farm Made Free Range Eggs 12 pcs", quantity: "12 piece", price: 243, mrp: 289, discount: null, image: "dairy/1041.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_42", name: "Harvest Gold White Bread", quantity: "300 g", price: 30, mrp: null, discount: null, image: "dairy/1042.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_43", name: "Amul Gold Milk", quantity: "1 l", price: 80, mrp: null, discount: 14, image: "dairy/1043.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_44", name: "Eggoz Nutrition White Protein Rich Eggs (10 pieces)", quantity: "10 pieces", price: 140, mrp: 164, discount: null, image: "dairy/1044.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_45", name: "Yakult Probiotic Drink", quantity: "5 x 65 ml", price: 90, mrp: null, discount: null, image: "dairy/1045.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_46", name: "Amul Garlic & Herbs Butter", quantity: "100 g", price: 66, mrp: null, discount: 14, image: "dairy/1046.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_47", name: "FruBon Low Fat Dahi/ Pouch Curd", quantity: "400 g", price: 30, mrp: 35, discount: null, image: "dairy/1047.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_48", name: "Mother Dairy Classic Pouch Pouch Curd", quantity: "390 g", price: 35, mrp: null, discount: null, image: "dairy/1048.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_49", name: "Britannia Vitarich Sandwich White Bread", quantity: "300 g", price: 25, mrp: null, discount: null, image: "dairy/1049.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_50", name: "Britannia Super White Bread", quantity: "400 g", price: 35, mrp: null, discount: null, image: "dairy/1050.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_51", name: "SILVER EGGS White Eggs", quantity: "30 pieces", price: 266, mrp: null, discount: 10, image: "dairy/1051.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_52", name: "FruBon Premium Cup Curd", quantity: "1 kg", price: 99, mrp: 110, discount: null, image: "dairy/1052.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_53", name: "English Oven Regular Burger Bun", quantity: "300 g", price: 55, mrp: null, discount: null, image: "dairy/1053.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_54", name: "The Health Factory Zero Maida Multigrain Bread", quantity: "250 g", price: 67, mrp: 70, discount: null, image: "dairy/1054.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_55", name: "The Health Factory Zero Maida Protein Bread", quantity: "250 g", price: 84, mrp: 85, discount: null, image: "dairy/1055.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_56", name: "SILVER EGGS Healthy Farm Fresh White Eggs", quantity: "6 pieces", price: 59, mrp: null, discount: null, image: "dairy/1056.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_57", name: "Epigamia Natural Greek Yogurt (85 g)", quantity: "85 g", price: 60, mrp: null, discount: null, image: "dairy/1057.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_58", name: "Epigamia Blueberry Flavoured Yogurt", quantity: "85 g", price: 60, mrp: null, discount: null, image: "dairy/1058.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_59", name: "Mother Dairy Mishti Doi", quantity: "80 g", price: 20, mrp: null, discount: null, image: "dairy/1059.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_60", name: "Amul Taaza Toned Milk", quantity: "200 ml", price: 16, mrp: null, discount: null, image: "dairy/1060.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_61", name: "Amul Yummy Plain Cheese Spread", quantity: "200 g", price: 109, mrp: null, discount: null, image: "dairy/1061.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_62", name: "English Oven Premium White Bread", quantity: "700 g", price: 60, mrp: null, discount: 11, image: "dairy/1062.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_63", name: "Abhi Vitamin D3 White Protein Rich Eggs", quantity: "24 pieces", price: 345, mrp: 389, discount: 6, image: "dairy/1063.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_64", name: "UPF Healthy Brown Eggs", quantity: "12 pieces", price: 181, mrp: 193, discount: null, image: "dairy/1064.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_65", name: "The Health Factory Sourdough Focaccia", quantity: "160 g", price: 75, mrp: null, discount: 9, image: "dairy/1065.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_66", name: "D'lecta Shredded Mozzarella Cheese", quantity: "140 g", price: 99, mrp: 109, discount: null, image: "dairy/1066.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_67", name: "English Oven Footlong Parmesan Oregano Sub", quantity: "150 g", price: 50, mrp: null, discount: 11, image: "dairy/1067.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_68", name: "Eggoz Nutrition White Protein Rich Eggs (6 pieces)", quantity: "6 pieces", price: 88, mrp: 99, discount: null, image: "dairy/1068.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_69", name: "FruBon White Desi Butter (Ghar ka Swaad)", quantity: "100 g", price: 69, mrp: 70, discount: null, image: "dairy/1069.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_70", name: "Epigamia Natural Greek Yogurt (400 g)", quantity: "400 g", price: 250, mrp: null, discount: null, image: "dairy/1070.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_71", name: "Mother Dairy Blueberry Flavoured Yogurt", quantity: "100 g", price: 35, mrp: null, discount: 14, image: "dairy/1071.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_72", name: "Eggoz Nutrition White Protein Rich Eggs (30 pieces)", quantity: "30 pieces", price: 360, mrp: 419, discount: 35, image: "dairy/1072.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_73", name: "D'lecta Processed Cheese Slices", quantity: "200 g", price: 104, mrp: 160, discount: 16, image: "dairy/1073.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_74", name: "The Natural Fresh White Protein Rich Eggs - 30 pieces", quantity: "30 pieces", price: 312, mrp: 375, discount: 24, image: "dairy/1074.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_75", name: "D'lecta 100% Mozzarella Pizza Cheese Block", quantity: "200 g", price: 117, mrp: 155, discount: null, image: "dairy/1075.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_76", name: "The Health Factory Zero Maida Bombay Pav", quantity: "156 g", price: 40, mrp: null, discount: null, image: "dairy/1076.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_77", name: "Mother Dairy FIT Life Homogenized Double Toned Milk (450 ml)", quantity: "450 ml", price: 32, mrp: null, discount: null, image: "dairy/1077.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_78", name: "English Oven Kulcha", quantity: "200 g", price: 45, mrp: null, discount: null, image: "dairy/1078.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_79", name: "Britannia 100% Whole Wheat Bread (No Maida)", quantity: "400 g", price: 60, mrp: null, discount: null, image: "dairy/1079.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_80", name: "Harvest Gold Bombay Pav", quantity: "350 g", price: 45, mrp: null, discount: null, image: "dairy/1080.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_81", name: "Amul Unsalted Butter", quantity: "100 g", price: 61, mrp: null, discount: 6, image: "dairy/1081.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_82", name: "Kalory Multigrain Bread", quantity: "400 g", price: 61, mrp: 65, discount: null, image: "dairy/1082.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_83", name: "The Health Factory Zero Maida Pizza Base", quantity: "140 g", price: 38, mrp: null, discount: null, image: "dairy/1083.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_84", name: "Kalory Atta Pav", quantity: "200 g", price: 39, mrp: 40, discount: 11, image: "dairy/1084.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_85", name: "Eggoz Nutra Plus Speciality Eggs (10 pieces)", quantity: "10 pieces", price: 141, mrp: 160, discount: 24, image: "dairy/1085.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_86", name: "Nature Good White Eggs", quantity: "10 pieces", price: 109, mrp: 145, discount: null, image: "dairy/1086.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_87", name: "Amul Cheese Block", quantity: "500 g", price: 290, mrp: null, discount: null, image: "dairy/1087.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_88", name: "Amul Spicy Garlic Cheese Spread", quantity: "200 g", price: 109, mrp: null, discount: 6, image: "dairy/1088.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_89", name: "D'lecta Natural Feta Cheese", quantity: "100 g", price: 107, mrp: 115, discount: null, image: "dairy/1089.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_90", name: "iD Malabar Paratha", quantity: "1 pack", price: 108, mrp: null, discount: 17, image: "dairy/1090.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_91", name: "Britannia Laughing Cow Cheese Slices (180 g)", quantity: "180 g", price: 109, mrp: 132, discount: 9, image: "dairy/1091.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_92", name: "Abhi Vitamin D3 White Protein Rich Eggs - 1 pack (6 pieces)", quantity: "6 pieces", price: 94, mrp: 104, discount: null, image: "dairy/1092.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_93", name: "Amul Buffalo A2 Milk", quantity: "1 l", price: 88, mrp: null, discount: null, image: "dairy/1093.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_94", name: "Amul Pizza Mozzarella Diced Cheese", quantity: "1 kg", price: 530, mrp: null, discount: 9, image: "dairy/1094.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_95", name: "UPF Healthy Brown Eggs - 6 pieces", quantity: "6 pieces", price: 90, mrp: 99, discount: null, image: "dairy/1095.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_96", name: "The Health Factory Zero Maida Garlic Bread", quantity: "156 g", price: 55, mrp: null, discount: null, image: "dairy/1096.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_97", name: "Amul White Unsalted Butter", quantity: "100 g", price: 61, mrp: null, discount: null, image: "dairy/1097.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_98", name: "English Oven Zero Maida Whole Wheat Bread", quantity: "350 g", price: 60, mrp: null, discount: 28, image: "dairy/1098.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_99", name: "Nature Good Brown Eggs", quantity: "6 pieces", price: 86, mrp: 120, discount: 12, image: "dairy/1099.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_100", name: "Go Cheese Four Shredded Cheese", quantity: "200 g", price: 140, mrp: 160, discount: null, image: "dairy/1100.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_101", name: "Kalory Garlic Bread", quantity: "250 g", price: 45, mrp: null, discount: 32, image: "dairy/1101.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_102", name: "Amul A+ Cheese Slices", quantity: "200 g", price: 115, mrp: 170, discount: null, image: "dairy/1102.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_103", name: "Epigamia Mixed Berries Flavoured Greek Yogurt", quantity: "85 g", price: 70, mrp: null, discount: null, image: "dairy/1103.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_104", name: "The Baker's Dozen Choco Chip Muffin", quantity: "45 g", price: 40, mrp: null, discount: null, image: "dairy/1104.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_105", name: "Yolkers Classic White Eggs", quantity: "10 pieces", price: 110, mrp: null, discount: null, image: "dairy/1105.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_106", name: "The Baker's Dozen Zero Maida Coconut Oats Cookies", quantity: "80 g", price: 83, mrp: null, discount: null, image: "dairy/1106.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_107", name: "Mother Dairy Raspberry Flavoured Yogurt", quantity: "100 g", price: 35, mrp: null, discount: null, image: "dairy/1107.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_108", name: "Epigamia Alphonso Mango Flavoured Greek Yogurt", quantity: "85 g", price: 60, mrp: null, discount: 10, image: "dairy/1108.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_109", name: "Abhi Gold+ Brown Eggs", quantity: "6 pieces", price: 103, mrp: 115, discount: null, image: "dairy/1109.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_110", name: "Yakult Light Probiotic Drink", quantity: "5 x 65 ml", price: 100, mrp: null, discount: null, image: "dairy/1110.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_111", name: "Amul Elaichi Shrikhand", quantity: "100 g", price: 28, mrp: null, discount: 6, image: "dairy/1111.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_112", name: "Cremeitalia Cream Cheese", quantity: "200 g", price: 289, mrp: 310, discount: null, image: "dairy/1210.png", inStock: true, deliveryTime: "21 minutes" },
  { productId: "dairy_113", name: "Amul Mango Shrikhand", quantity: "100 g", price: 28, mrp: null, discount: null, image: "dairy/1113.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_114", name: "Kalory Burger Bun", quantity: "200 g", price: 43, mrp: 45, discount: 29, image: "dairy/1114.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_115", name: "D'lecta Chilli Cheese Slices", quantity: "10 x 20 g", price: 116, mrp: 165, discount: 5, image: "dairy/1115.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_116", name: "Kalory White Bread", quantity: "600 g", price: 52, mrp: 55, discount: null, image: "dairy/1116.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_117", name: "Kalory Pizza Base", quantity: "200 g", price: 39, mrp: 40, discount: null, image: "dairy/1117.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_118", name: "Epigamia Strawberry Flavoured Greek Yogurt", quantity: "85 g", price: 70, mrp: null, discount: null, image: "dairy/1118.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_119", name: "The Health Factory Zero Maida Burger Bun", quantity: "120 g", price: 37, mrp: null, discount: 6, image: "dairy/1119.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_120", name: "D'lecta 100% Cheddar Cheese Slices", quantity: "200 g", price: 195, mrp: 209, discount: null, image: "dairy/1120.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_121", name: "Amul Slim 'n' Trim Skimmed Milk (Zero Cholesterol)", quantity: "1 l", price: 82, mrp: null, discount: 25, image: "dairy/1121.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_122", name: "Go Cheese Pizza Mozzarella & Cheddar Diced Cheese", quantity: "200 g", price: 115, mrp: 155, discount: null, image: "dairy/1122.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_123", name: "The Health Factory Zero Maida Milk Bread", quantity: "250 g", price: 60, mrp: null, discount: null, image: "dairy/1123.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_124", name: "iD Wheat Lachha Paratha", quantity: "1 pack", price: 108, mrp: null, discount: 13, image: "dairy/1124.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_125", name: "The Natural Fresh White Protein Rich Eggs - 6 pieces", quantity: "6 pieces", price: 82, mrp: 95, discount: null, image: "dairy/1125.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_126", name: "Epigamia Strawberry Flavoured Yogurt", quantity: "85 g", price: 60, mrp: null, discount: null, image: "dairy/1126.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_127", name: "Kalory Kulcha", quantity: "200 g", price: 39, mrp: 40, discount: null, image: "dairy/1127.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_128", name: "Epigamia Turbo Mixed Berries Flavoured Protein Yogurt", quantity: "140 g", price: 125, mrp: null, discount: null, image: "dairy/1128.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_129", name: "Amul Cream Cheese", quantity: "180 g", price: 118, mrp: null, discount: 22, image: "dairy/1129.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_130", name: "Mother Dairy Cheese Cubes", quantity: "180 g", price: 105, mrp: 135, discount: null, image: "dairy/1130.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_131", name: "D'lecta Parmesan Extra Hard Cheese Block", quantity: "100 g", price: 350, mrp: null, discount: null, image: "dairy/1131.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_132", name: "Britannia Laughing Cow Cheese Slices (90 g)", quantity: "90 g", price: 75, mrp: null, discount: 5, image: "dairy/1132.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_133", name: "Kalory 100% Wheat Bread", quantity: "400 g", price: 57, mrp: 60, discount: 32, image: "dairy/1133.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_134", name: "Go Cheese Slices", quantity: "476 g", price: 325, mrp: 485, discount: null, image: "dairy/1134.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_135", name: "Mother Dairy Salted Butter (500 g)", quantity: "500 g", price: 285, mrp: null, discount: null, image: "dairy/1135.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_136", name: "The Baker's Dozen Zero Maida Chocolate Brownie", quantity: "55 g", price: 79, mrp: null, discount: null, image: "dairy/1136.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_137", name: "Yolkers Classic White Eggs (6 pieces)", quantity: "6 pieces", price: 66, mrp: null, discount: null, image: "dairy/1137.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_138", name: "The Baker's Dozen Zero Maida Banana Walnut Pound Cake, Whole Wheat", quantity: "150 g", price: 185, mrp: null, discount: 22, image: "dairy/1138.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_139", name: "Mother Dairy Cheese Slices", quantity: "200 g", price: 124, mrp: 160, discount: 18, image: "dairy/1139.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_140", name: "FruBon Pasteurized Toned Cup Curd", quantity: "180 g", price: 18, mrp: 22, discount: null, image: "dairy/1140.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_141", name: "Epigamia Turbo Protein Yogurt", quantity: "140 g", price: 125, mrp: null, discount: 7, image: "dairy/1141.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_142", name: "D'lecta Cream Cheese", quantity: "150 g", price: 175, mrp: 189, discount: 34, image: "dairy/1142.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_143", name: "D'lecta Processed Cheese Spread - Improved Recipe", quantity: "150 g", price: 65, mrp: 99, discount: null, image: "dairy/1143.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_144", name: "Kalory Brown Bread", quantity: "350 g", price: 48, mrp: 50, discount: null, image: "dairy/1144.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_145", name: "Harvest Gold Premium Quality Burger Bun", quantity: "300 g", price: 45, mrp: null, discount: null, image: "dairy/1145.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_146", name: "The Baker's Dozen Choco Chip Chocolate Pound Cake", quantity: "150 g", price: 172, mrp: null, discount: null, image: "dairy/1146.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_147", name: "Amul Badam Pista Shrikhand", quantity: "200 g", price: 57, mrp: null, discount: null, image: "dairy/1147.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_148", name: "Amul Kesar Shrikhand", quantity: "500 g", price: 130, mrp: null, discount: 8, image: "dairy/1148.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_149", name: "Britannia Laughing Cow Cheese Cubes", quantity: "200 g", price: 116, mrp: 127, discount: null, image: "dairy/1149.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_150", name: "The Baker's Dozen Grissini Baked Chilli Garlic Bread Sticks", quantity: "100 g", price: 129, mrp: null, discount: 24, image: "dairy/1150.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_151", name: "D'lecta Cheese Cubes (10 cubes)", quantity: "200 g", price: 124, mrp: 165, discount: null, image: "dairy/1151.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_152", name: "Amul Camel Milk", quantity: "200 ml", price: 25, mrp: null, discount: null, image: "dairy/1152.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_153", name: "UPF Cage Free Brown Eggs", quantity: "6 piece", price: 129, mrp: null, discount: 11, image: "dairy/1153.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_154", name: "FruBon Classic Blueberry Flavoured Yogurt", quantity: "100 g", price: 31, mrp: 35, discount: null, image: "dairy/1154.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_155", name: "Mother Dairy Toned Milk", quantity: "1 l", price: 75, mrp: null, discount: null, image: "dairy/1155.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_156", name: "Andaah Natural +VitaD White Protein Rich Eggs", quantity: "12 pieces", price: 175, mrp: null, discount: 7, image: "dairy/1156.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_157", name: "D'lecta 100% Cheddar Cheese Block", quantity: "200 g", price: 185, mrp: 199, discount: 25, image: "dairy/1157.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_158", name: "Go Squares Processed Cheese Cubes", quantity: "200 g", price: 115, mrp: 155, discount: 5, image: "dairy/1158.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_159", name: "FruBon High Protein Plain Greek Yogurt", quantity: "85 g", price: 57, mrp: 60, discount: 20, image: "dairy/1159.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_160", name: "FruBon Mishti Doi", quantity: "100 g", price: 16, mrp: 20, discount: null, image: "dairy/1160.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_161", name: "The Baker's Dozen Zero Maida Vanilla Pound Cake, Whole Wheat", quantity: "150 g", price: 163, mrp: null, discount: null, image: "dairy/1161.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_162", name: "Epigamia Wild Raspberry Flavoured Yogurt", quantity: "85 g", price: 60, mrp: null, discount: 10, image: "dairy/1162.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_163", name: "D'lecta Mozzarella Cheese - Shredded", quantity: "500 g", price: 295, mrp: 330, discount: null, image: "dairy/1163.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_164", name: "Amul Lite Milk Fat Spread", quantity: "100 g", price: 45, mrp: null, discount: 11, image: "dairy/1164.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_165", name: "FruBon Farm Strawberry Flavoured Yogurt", quantity: "100 g", price: 31, mrp: 35, discount: null, image: "dairy/1165.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_166", name: "Nestle a+ Toned Milk", quantity: "1 l", price: 108, mrp: null, discount: null, image: "dairy/1166.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_167", name: "Amul Punchy Pepper Cheese Spread", quantity: "200 g", price: 109, mrp: null, discount: null, image: "dairy/1167.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_168", name: "The Baker's Dozen Choco Filled Donut Cake", quantity: "42 g", price: 30, mrp: null, discount: 9, image: "dairy/1168.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_169", name: "The Baker's Dozen Fruit Cake Rusk (Zero Maida, High Protein)", quantity: "100 g", price: 109, mrp: 120, discount: 11, image: "dairy/1169.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_170", name: "FruBon Alphonso Mango Flavoured Yogurt", quantity: "100 g", price: 31, mrp: 35, discount: null, image: "dairy/1170.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_171", name: "Andaah Natural + VitaD White Protein Rich Eggs", quantity: "6 pieces", price: 88, mrp: null, discount: null, image: "dairy/1171.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_172", name: "The Baker's Dozen Whole Wheat Baked Lavash Flatbread Crisp for Dip", quantity: "100 g", price: 129, mrp: null, discount: null, image: "dairy/1172.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_173", name: "FruBon Elaichi Shrikhand", quantity: "50 g", price: 15, mrp: null, discount: null, image: "dairy/1173.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_174", name: "The Baker's Dozen Choco Chip Chocolate Cookies", quantity: "60 g", price: 60, mrp: null, discount: 13, image: "dairy/1174.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_175", name: "Go Mozzarella Diced Cheese", quantity: "500 g", price: 295, mrp: 340, discount: null, image: "dairy/1175.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_176", name: "Amul Cheddar Cheese Block", quantity: "250 g", price: 180, mrp: null, discount: 39, image: "dairy/1176.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_177", name: "Britannia Laughing Cow Cheese Slices", quantity: "400 g", price: 298, mrp: 490, discount: null, image: "dairy/1177.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_178", name: "Delicious Cholesterol Free Fat Spread", quantity: "100 g", price: 22, mrp: null, discount: null, image: "dairy/1178.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_179", name: "Nestle a+ Slim Skimmed Milk", quantity: "1 l", price: 97, mrp: null, discount: null, image: "dairy/1179.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_180", name: "Yolkers Classic White Eggs", quantity: "30 pieces", price: 305, mrp: null, discount: null, image: "dairy/1180.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_181", name: "The Baker's Dozen Zero Maida Butter Garlic Toast, Whole Wheat", quantity: "90 g", price: 119, mrp: null, discount: null, image: "dairy/1181.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_182", name: "The Baker's Dozen Nankhatai Ghee Cookies Cookies", quantity: "105 g", price: 139, mrp: null, discount: null, image: "dairy/1182.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_183", name: "The Baker's Dozen High Protein Peanut Butter Cookies", quantity: "75 g", price: 98, mrp: null, discount: 12, image: "dairy/1183.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_184", name: "Britannia Laughing Cow Cheese Block with Mozzarella", quantity: "200 g", price: 111, mrp: 127, discount: null, image: "dairy/1184.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_185", name: "Epigamia Alphonso Mango Flavoured Yogurt", quantity: "75 g", price: 35, mrp: null, discount: 16, image: "dairy/1185.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_186", name: "Nutralite DoodhShakti Probiotic Butter (Tub)", quantity: "500 g", price: 257, mrp: 309, discount: null, image: "dairy/1186.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_187", name: "Andaah Brown Eggs + Vita D", quantity: "6 pieces", price: 100, mrp: null, discount: null, image: "dairy/1187.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_188", name: "The Baker's Dozen Elaichi Rusk (Zero Maida, High Protein)", quantity: "80 g", price: 40, mrp: null, discount: null, image: "dairy/1188.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_189", name: "The Baker's Dozen Zero Maida Banana Bread, Whole Wheat", quantity: "150 g", price: 175, mrp: null, discount: null, image: "dairy/1189.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_190", name: "The Baker's Dozen Dark Chocolate Cookies", quantity: "100 g", price: 111, mrp: null, discount: null, image: "dairy/1190.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_191", name: "Amul Real Mango Amrakhand", quantity: "500 g", price: 115, mrp: null, discount: null, image: "dairy/1191.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_192", name: "Amul Elaichi Shrikhand", quantity: "200 g", price: 52, mrp: null, discount: 20, image: "dairy/1192.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_193", name: "Mother Dairy Creamy Plain Cheese Spread", quantity: "180 g", price: 88, mrp: 110, discount: null, image: "dairy/1193.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_194", name: "Epigamia Vanilla Bean Flavoured Greek Yogurt", quantity: "85 g", price: 60, mrp: null, discount: 6, image: "dairy/1194.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_195", name: "Nutralite DoodhShakti Probiotic Butter", quantity: "100 g", price: 56, mrp: 60, discount: 14, image: "dairy/1195.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_196", name: "Wingreens Farms Multigrain Baked Flat Bread Sticks", quantity: "100 g", price: 128, mrp: 150, discount: null, image: "dairy/1196.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_197", name: "Epigamia Strawberry Smoothie Greek Yogurt Drink", quantity: "180 ml", price: 80, mrp: null, discount: 17, image: "dairy/1197.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_198", name: "Go Plain Cheese Spread", quantity: "200 g", price: 95, mrp: 115, discount: null, image: "dairy/1198.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_199", name: "The Baker's Dozen High Protein Ragi Crackers Chips", quantity: "100 g", price: 129, mrp: null, discount: null, image: "dairy/1199.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_200", name: "Epigamia Everyday Mango Flavoured Yogurt", quantity: "75 g", price: 25, mrp: null, discount: null, image: "dairy/1200.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_201", name: "Amul Mango Shrikhand", quantity: "500 g", price: 115, mrp: null, discount: 27, image: "dairy/1201.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_202", name: "Mother Dairy Cheese Slices", quantity: "480 g", price: 292, mrp: 405, discount: 13, image: "dairy/1202.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_203", name: "Nutralite DoodhShakti Probiotic Butter (500 g)", quantity: "500 g", price: 250, mrp: 290, discount: null, image: "dairy/1203.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_204", name: "The Baker's Dozen Protein Chocolate Muffin", quantity: "45 g", price: 65, mrp: null, discount: null, image: "dairy/1204.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_205", name: "Epigamia Everyday Lychee Flavoured Yogurt", quantity: "75 g", price: 25, mrp: null, discount: null, image: "dairy/1205.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_206", name: "The Baker's Dozen Fresh Orange Pound Cake", quantity: "150 g", price: 163, mrp: null, discount: 10, image: "dairy/1206.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_207", name: "Pintola Unsweetened Creamy Almond Butter", quantity: "200 g", price: 358, mrp: 398, discount: 25, image: "dairy/1207.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_208", name: "Mother Dairy Cheese Block", quantity: "200 g", price: 112, mrp: 150, discount: 39, image: "dairy/1208.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_209", name: "D'lecta Processed Cheese Slices (400 g)", quantity: "400 g", price: 183, mrp: 300, discount: 5, image: "dairy/1209.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_210", name: "FruBon Blueberry Flavoured Greek Yogurt", quantity: "85 g", price: 57, mrp: 60, discount: 17, image: "dairy/1210.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_211", name: "Go Jalapeno Cheese Spread", quantity: "200 g", price: 95, mrp: 115, discount: null, image: "dairy/1211.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_212", name: "The Baker's Dozen Zero Maida Carrot Walnut Pound Cake, Whole Wheat", quantity: "150 g", price: 172, mrp: null, discount: 24, image: "dairy/1212.jpg", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_213", name: "D'lecta Processed Cheese Block", quantity: "200 g", price: 113, mrp: 150, discount: 5, image: "dairy/1213.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_214", name: "FruBon High Protein Flavoured Greek Yogurt (Strawberry)", quantity: "85 g", price: 57, mrp: 60, discount: null, image: "dairy/1214.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_215", name: "The Baker's Dozen Rich Chocolate Pound Cake", quantity: "150 g", price: 163, mrp: null, discount: null, image: "dairy/1215.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_216", name: "The Baker's Dozen Pista Badam Cookies", quantity: "60 g", price: 59, mrp: null, discount: 17, image: "dairy/1216.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_217", name: "Go Olive & Herbs Cheese Spread", quantity: "200 g", price: 95, mrp: 115, discount: 35, image: "dairy/1217.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_218", name: "Go Pizza Cheese Block", quantity: "200 g", price: 120, mrp: 185, discount: null, image: "dairy/1218.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_219", name: "Amul Pizza Processed Cheese Block", quantity: "200 g", price: 124, mrp: 125, discount: null, image: "dairy/1219.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_220", name: "American Garden Plain Bread Crumbs", quantity: "425 g", price: 345, mrp: null, discount: 25, image: "dairy/1220.png", inStock: true, deliveryTime: "14 minutes" },
  { productId: "dairy_221", name: "Nature Vit Cheddar Cheese Powder Seasoning", quantity: "250 g", price: 299, mrp: 400, discount: null, image: "dairy/1221.png", inStock: true, deliveryTime: "21 minutes" }
]

const Tobacco = [
  { productId: "tobacco_1", name: "Perfect Rolled Cones (Natural) - Bongchie", quantity: " 3 pack", price: 45, mrp: null, discount: null, image: "tobacco/101.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_2", name: "Ultimate Rolling Paper with Filter Tips & Crushing Tray (King Size, Unbleached) - Mozo", quantity: " 32 pieces", price: 90, mrp: null, discount: null, image: "tobacco/102.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_3", name: "Brown Ripper Rolling Paper 32 Leaves + 32 Roaches - Stash Pro", quantity: " 64 pieces", price: 120, mrp: null, discount: null, image: "tobacco/103.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_4", name: "Brown Rolling Paper (King Size) - Stash Pro", quantity: " 1 unit (32 pieces)", price: 50, mrp: null, discount: null, image: "tobacco/104.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_5", name: "Carbon Filters (7 mm) - SLIMJIM", quantity: " 10 pieces", price: 225, mrp: null, discount: null, image: "tobacco/105.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_6", name: "Brown Rolling Paper 64 sheets + 64 tips & Crushing Tray - Blaze Up", quantity: " 64 + 64 pieces", price: 199, mrp: 200, discount: null, image: "tobacco/106.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "tobacco_7", name: "Ultimate Rolling Paper with Filter Tips & Crushing Tray (King Size, Bleached) - Mozo", quantity: " 32 Leaves + 32 Filters", price: 80, mrp: null, discount: null, image: "tobacco/108.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_8", name: "Perfect Rolling Paper (Pink) - Bongchie", quantity: " 3 pack", price: 45, mrp: null, discount: null, image: "tobacco/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_9", name: "Super Slim Brown Rolling Paper - Stash Pro", quantity: " 32 pieces", price: 55, mrp: null, discount: null, image: "tobacco/110.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_10", name: "Perforated Wide Tips Roach - Raw", quantity: " 50 pieces", price: 49, mrp: 50, discount: null, image: "tobacco/111.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_11", name: "Brown Rolling Paper Cones - Stash Pro", quantity: " 6 pieces", price: 90, mrp: null, discount: null, image: "tobacco/112.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_12", name: "Thins Pre-Rolled Rolling Paper - LIT", quantity: " 1 pack", price: 25, mrp: null, discount: null, image: "tobacco/113.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_13", name: "Perfect Pre Rolled Cones - Bongchie", quantity: " 10 pieces", price: 150, mrp: null, discount: null, image: "tobacco/114.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_14", name: "Metallic Herb Grinder/ Crusher - Outontrip", quantity: " 1 unit", price: 249, mrp: 250, discount: null, image: "tobacco/115.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_15", name: "Black Slim Rolling Paper (King Size) - Raw", quantity: " 32 pieces", price: 99, mrp: 100, discount: null, image: "tobacco/116.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_16", name: "Classic Filter Tips & Rolling Paper (King Size) - Raw", quantity: " 32 + 32 pieces", price: 149, mrp: 150, discount: null, image: "tobacco/117.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_17", name: "Brown Pre Rolled Cones - Cannapro", quantity: " 6 pieces", price: 59, mrp: 60, discount: null, image: "tobacco/118.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_18", name: "Colour Roach - Stash Pro", quantity: " 32 sheets", price: 50, mrp: null, discount: null, image: "tobacco/119.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_19", name: "Bio-Degradeble Crusher - Stash Pro", quantity: " 1 piece", price: 300, mrp: null, discount: null, image: "tobacco/120.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_20", name: "Brown Classic Slim Rolling Paper (King Size) - Raw", quantity: " 32 pieces", price: 79, mrp: 80, discount: null, image: "tobacco/121.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_21", name: "White Rolling Paper Cones - Stash Pro", quantity: " 6 pieces", price: 90, mrp: null, discount: null, image: "tobacco/122.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_22", name: "Pop N Puff Rolling Paper (Assorted) - Bongchie", quantity: " 4 packs", price: 80, mrp: null, discount: null, image: "tobacco/123.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_23", name: "Perfect Ultra Thin Pre Rolled Cones - Bongchie", quantity: " 6 pieces", price: 90, mrp: null, discount: null, image: "tobacco/124.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_24", name: "Brown Rolling Paper + Roach with Crushing Tray - Stash Pro", quantity: " 1 pack", price: 222, mrp: null, discount: null, image: "tobacco/125.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_25", name: "Pre-rolled Rose Blunt Rolling Paper - Bongchie", quantity: " 1 unit", price: 120, mrp: null, discount: null, image: "tobacco/126.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_26", name: "Burning Desire Pink Cone Rolling Paper - Stash Pro", quantity: " 6 pieces", price: 100, mrp: null, discount: null, image: "tobacco/127.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_27", name: "Ripper Tipper Brown Rolling Paper (Small) - Stash Pro", quantity: " 40 + 40 pieces", price: 120, mrp: null, discount: null, image: "tobacco/128.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_28", name: "Dollar Pre-rolled Rolling Paper - Bongchie", quantity: " 3 packs", price: 60, mrp: null, discount: null, image: "tobacco/129.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_29", name: "White Ripper Tipper Rolling Paper with Roaches - Stash Pro", quantity: " 32 + 32 pieces", price: 100, mrp: null, discount: null, image: "tobacco/130.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_30", name: "Perfect Rolled Cones (White) - Bongchie", quantity: " 3 pack", price: 45, mrp: null, discount: null, image: "tobacco/131.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_31", name: "Flavoured Pre Rolled Cones - Sesh", quantity: " 6 rolls", price: 119, mrp: 120, discount: null, image: "tobacco/132.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_32", name: "Thins Pre Rolled Cones - LIT", quantity: " 3 pack (6 pieces)", price: 60, mrp: null, discount: null, image: "tobacco/133.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_33", name: "Elite Pack Hemp Rolling Paper & Tips - LIT", quantity: " 33 pieces", price: 120, mrp: null, discount: 10, image: "tobacco/134.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_34", name: "Rolling Paper Pocket Kit - Sesh", quantity: " 1 pack", price: 225, mrp: 250, discount: null, image: "tobacco/135.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_35", name: "420 Double Booklet Brown Rolling Paper & Filter - LIT", quantity: " 66 pieces", price: 222, mrp: null, discount: null, image: "tobacco/136.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_36", name: "Glass Filter Tip Reusable Smoking Filter with perfect roll - Bongchie", quantity: " 1 unit", price: 55, mrp: null, discount: null, image: "tobacco/137.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_37", name: "Perfect Slim & Pre-rolled Rolling Paper - Bongchie", quantity: " 3 pieces", price: 90, mrp: null, discount: null, image: "tobacco/138.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_38", name: "Thrice a Day Pure Hemp Rolling Paper - Bongchie", quantity: " 10 packs", price: 90, mrp: null, discount: null, image: "tobacco/139.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_39", name: "Super Slim White Rolling Paper - Stash Pro", quantity: " 32 pieces", price: 55, mrp: null, discount: null, image: "tobacco/140.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_40", name: "Brown Rolling Paper (Small) - Stash Pro", quantity: " 40 pieces", price: 45, mrp: null, discount: null, image: "tobacco/141.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_41", name: "Black Organic Hemp Slim Rolling Paper (King Size) - Raw", quantity: " 32 pieces", price: 119, mrp: 120, discount: null, image: "tobacco/142.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_42", name: "White Rolling Paper Tips - Elements", quantity: " 50 pieces", price: 49, mrp: 50, discount: null, image: "tobacco/143.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_43", name: "Thrice a Day Black Edition Rolling Paper - Bongchie", quantity: " 10 packs", price: 100, mrp: null, discount: 17, image: "tobacco/144.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_44", name: "Chandan Calcutta Mitha Pan Mouth Freshener", quantity: " 90 g", price: 170, mrp: 205, discount: null, image: "tobacco/145.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_45", name: "Mozo without Filter (Natural) Rolling Paper - Bongchie", quantity: " 1 pack", price: 50, mrp: null, discount: null, image: "tobacco/146.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_46", name: "Emergency White Rolling Paper with Roach - Stash Pro", quantity: " 10 pieces", price: 99, mrp: null, discount: null, image: "tobacco/147.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_47", name: "Perfect King Size Pre Rolled Cones - Bongchie", quantity: " 10 pieces", price: 150, mrp: null, discount: null, image: "tobacco/148.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_48", name: "Thrice a Day Purple Haze Rolling Paper - Bongchie", quantity: " 10 packs", price: 100, mrp: null, discount: null, image: "tobacco/149.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_49", name: "Emergency Brown Rolling Paper with Roach - Stash Pro", quantity: " 10 x 4 pieces", price: 99, mrp: null, discount: null, image: "tobacco/150.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_50", name: "Herb Mixing Rolling Tray - Stash Pro", quantity: " 1 piece", price: 300, mrp: null, discount: null, image: "tobacco/151.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_51", name: "Pink Rolling Paper (King Size Slim) - Stash Pro", quantity: " 32 sheets", price: 70, mrp: null, discount: null, image: "tobacco/152.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_52", name: "Small Rolling Paper Cone (84 mm) - Stash Pro", quantity: " 6 pieces", price: 90, mrp: null, discount: null, image: "tobacco/153.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_53", name: "Medium 3 layer Crusher with Cleaning Mesh - Stash Pro", quantity: " 1 piece", price: 650, mrp: null, discount: 9, image: "tobacco/154.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_54", name: "Metal Rolling Tray by LIT (Design may Vary)", quantity: " 1 unit", price: 315, mrp: 349, discount: null, image: "tobacco/155.jpg", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_55", name: "Pyramid Rice Handcrafted Pre Rolled Cones - LIT", quantity: " 6 pieces", price: 88, mrp: null, discount: null, image: "tobacco/156.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_56", name: "White Rolling Paper (King Size Slim) - Stash Pro", quantity: " 32 sheets", price: 50, mrp: null, discount: null, image: "tobacco/157.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_57", name: "Emergency Burning Desire Pink Rolling Paper #NAME? - Stash Pro", quantity: " 10 x 4 pieces", price: 149, mrp: null, discount: null, image: "tobacco/158.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_58", name: "Thrice A Day Rolling Paper (Natural) - Bongchie", quantity: " 10 pieces", price: 90, mrp: null, discount: null, image: "tobacco/159.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_59", name: "Unbleached Thins Pre Rolled Cones Jar - LIT", quantity: " 50 pieces", price: 420, mrp: null, discount: null, image: "tobacco/160.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_60", name: "Perfect Party Pre Rolled Cones (White) - Bongchie", quantity: " 3 pieces", price: 80, mrp: null, discount: null, image: "tobacco/161.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_61", name: "Hemp King Size Rolling Paper - SLIMJIM", quantity: " 1 unit", price: 100, mrp: null, discount: null, image: "tobacco/162.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_62", name: "Glassy Wrap Clear Rolling Paper & Tips - LIT", quantity: " 50 pieces", price: 300, mrp: null, discount: null, image: "tobacco/163.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_63", name: "Small 2 layer Crusher with Cleaning Mesh - Stash Pro", quantity: " 1 piece", price: 550, mrp: null, discount: null, image: "tobacco/164.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_64", name: "Mozo without Filter Rolling Paper (White) - Bongchie", quantity: " 1 pack", price: 50, mrp: null, discount: null, image: "tobacco/165.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_65", name: "Mozo 1/4 without Filter Rolling Paper (Brown) - Bongchie", quantity: " 1 pack", price: 60, mrp: null, discount: null, image: "tobacco/166.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_66", name: "Mozo 1/4 with Filter Rolling Paper (White) - Bongchie", quantity: " 1 unit", price: 100, mrp: null, discount: null, image: "tobacco/167.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_67", name: "Tripod 3 Pre-Rolled Cone Holder - SLIMJIM", quantity: " 1 unit", price: 249, mrp: null, discount: null, image: "tobacco/168.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_68", name: "Mozo 1/4 Rolling Paper without Filter (White) - Bongchie", quantity: " 1 pack", price: 60, mrp: null, discount: null, image: "tobacco/169.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_69", name: "Pyramid Giant Pre Rolled Cones - LIT", quantity: " 1 unit", price: 199, mrp: null, discount: null, image: "tobacco/170.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_70", name: "Pyramid Organic Pre Rolled Cones - LIT", quantity: " 32 pieces", price: 420, mrp: null, discount: null, image: "tobacco/171.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_71", name: "Pyramid Pre Rolled Cones - LIT", quantity: " 32 pieces", price: 420, mrp: null, discount: 10, image: "tobacco/172.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_72", name: "420 Rolling Tray - LIT", quantity: " 1 unit", price: 400, mrp: 449, discount: null, image: "tobacco/173.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "tobacco_73", name: "Aluminum Fine Herb Crusher - Stash Pro", quantity: " 1 unit", price: 1000, mrp: null, discount: null, image: "tobacco/174.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_74", name: "Printed Designer Roach Pad - SLIMJIM", quantity: " 1 pack", price: 50, mrp: null, discount: 10, image: "tobacco/175.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_75", name: "Slim Holder - LIT", quantity: " 1 piece", price: 539, mrp: 599, discount: null, image: "tobacco/176.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_76", name: "Small Metal Rolling Tray (Colour may Vary) - Stash Pro", quantity: " 1 piece", price: 350, mrp: null, discount: null, image: "tobacco/177.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "tobacco_77", name: "Thins Pre Rolled Cones Jar - LIT", quantity: " 1 pack (50 pieces)", price: 420, mrp: null, discount: null, image: "tobacco/178.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_78", name: "UFO Grinder Crusher - Stash Pro", quantity: " 1 unit", price: 1600, mrp: null, discount: null, image: "tobacco/179.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "tobacco_79", name: "White Party Cone Rolling Paper - Stash Pro", quantity: " 1 pack (3 pieces)", price: 80, mrp: null, discount: null, image: "tobacco/180.png", inStock: true, deliveryTime: "13 minutes" }
];

const Munchies = [
  { productId: "munchies_1", name: "Beanly Choco Hazelnut Spread with Breadsticks", quantity: " 52 g", price: 99, mrp: 133, discount: null, image: "munchies/101.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_2", name: "Lo! Foods Gluten Free Ragi Chips Roasted Healthy Snacks", quantity: " 75 g", price: 99, mrp: null, discount: null, image: "munchies/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_3", name: "Protein Chef Baked Coated Peanuts (Masala Roasted Healthy Snacks)", quantity: " 50 g", price: 70, mrp: null, discount: 15, image: "munchies/103.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_4", name: "Red Rock Deli Potato Chips (Baked Olive & Greek Salad)", quantity: " 53 g", price: 51, mrp: 60, discount: null, image: "munchies/104.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_5", name: "Kettle Studio Rock Sea Salt & English Vinegar Potato Chips", quantity: " 113 g", price: 99, mrp: null, discount: null, image: "munchies/105.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "munchies_6", name: "Nongshim Shrimp Flavoured Hot & Spicy Crackers Chips", quantity: " 75 g", price: 125, mrp: null, discount: 25, image: "munchies/106.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "munchies_7", name: "Beanly Dark Chocolate Spread with Breadsticks", quantity: " 52 g", price: 99, mrp: 133, discount: 10, image: "munchies/105.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_8", name: "Kettle Studio Himalayan Pink Salt Potato Chips", quantity: " 56 g", price: 44, mrp: 49, discount: null, image: "munchies/108.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_9", name: "Kettle Studio Air Fried Spicy Dill Pickle Potato Chips", quantity: " 80 g", price: 99, mrp: null, discount: null, image: "munchies/109.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "munchies_10", name: "Kettle Studio Lime & Chilli Wafers", quantity: " 140 g", price: 80, mrp: null, discount: null, image: "munchies/110.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "munchies_11", name: "Kettle Studio Sharp Jalapenos & Cream Cheese Potato Chips", quantity: " 113 g", price: 99, mrp: null, discount: null, image: "munchies/111.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "munchies_12", name: "Svaras Roasted Khakhra - Handpicked 5 Flavour Pack", quantity: " 5 x 50 g", price: 250, mrp: null, discount: 10, image: "munchies/112.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "munchies_13", name: "Kettle Studio Mature Cheddar & Red Onions Potato Chips", quantity: " 56 g", price: 44, mrp: 49, discount: 26, image: "munchies/113.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_14", name: "Orion Korean Kimchi K Snack Onion Rings", quantity: " 70 g", price: 44, mrp: 60, discount: null, image: "munchies/114.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_15", name: "Protein Chef Baked Bikaneri Bhujia (No Palm Oil Roasted Snacks)", quantity: " 80 g", price: 99, mrp: null, discount: null, image: "munchies/115.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_16", name: "Lay's Extra Barbecue Potato Chips", quantity: " 50 g", price: 190, mrp: 199, discount: 5, image: "munchies/116.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_17", name: "Lo! Foods Keto Murukku Diet Chakli Healthy Snack (No Palm Oil)", quantity: " 100 g", price: 150, mrp: 159, discount: null, image: "munchies/117.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_18", name: "Protein Chef Double Protein Crunchy Soya Sticks (No Palm Oil)", quantity: " 65 g", price: 59, mrp: null, discount: null, image: "munchies/118.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_19", name: "Protein Chef Madras Mixture Namkeen Healthy Snack (10g Protein)", quantity: " 90 g", price: 99, mrp: null, discount: 5, image: "munchies/119.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_20", name: "Cheetos Flamin Hot Crunchy Puffs", quantity: " 28.3 g", price: 150, mrp: 159, discount: null, image: "munchies/120.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_21", name: "Lay's Potato Chips (Sour Cream & Onion)", quantity: " 50 g", price: 190, mrp: 199, discount: null, image: "munchies/106.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_22", name: "Kab's Jackpot Chilli Lemon Stix Crisps", quantity: " 80 g", price: 65, mrp: null, discount: null, image: "munchies/101.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_23", name: "Lay's Crunch Extra Cheese Potato Chips", quantity: " 50 g", price: 190, mrp: 199, discount: null, image: "munchies/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_24", name: "Lay's Potato Chips (Hot & Spicy)", quantity: " 50 g", price: 190, mrp: 199, discount: 11, image: "munchies/103.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_25", name: "Lay's Stax Original Potato Chips", quantity: " 155.9 g", price: 266, mrp: 299, discount: null, image: "munchies/104.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_26", name: "Pringles Barbeque Flavored Potato Crisps", quantity: " 158 g", price: 329, mrp: null, discount: null, image: "munchies/105.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_27", name: "Kab's Jackpot Fire Balls Snack", quantity: " 60 g", price: 65, mrp: null, discount: null, image: "munchies/106.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_28", name: "Protein Chef Baked Coated Tangy Tomato Peanuts", quantity: " 50 g", price: 75, mrp: null, discount: 40, image: "munchies/110.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_29", name: "Moi Soi Brown Rice Paper", quantity: " 100 g", price: 148, mrp: 250, discount: null, image: "munchies/108.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_30", name: "Mega Chips Kebab Flavoured Potato Chips", quantity: " 50 g", price: 141, mrp: null, discount: null, image: "munchies/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_31", name: "Lay's Potato Chips (Nori Seaweed)", quantity: " 50 g", price: 190, mrp: 199, discount: 11, image: "munchies/110.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_32", name: "Lay's Stax Mesquite Barbecue Potato Chips", quantity: " 135 g", price: 266, mrp: 299, discount: null, image: "munchies/111.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_33", name: "Kab's Jackpot Schezwan Chilli Crisps", quantity: " 80 g", price: 65, mrp: null, discount: null, image: "munchies/112.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_34", name: "Kab's Jackpot Crispy Potato Crackers (Hot & Spicy)", quantity: " 50 g", price: 65, mrp: null, discount: null, image: "munchies/113.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_35", name: "Pringles Cheddar & Sour Cream Potato Crisps", quantity: " 158 g", price: 329, mrp: null, discount: 5, image: "munchies/114.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_36", name: "Lo! Foods Keto Mixture Namkeen - High Protein Healthy Snack", quantity: " 100 g", price: 150, mrp: 159, discount: null, image: "munchies/115.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_37", name: "Meiji Yan Yan Strawberry Dip Biscuit Sticks", quantity: " 50 g", price: 161, mrp: 169, discount: 11, image: "munchies/116.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_38", name: "Lay's Stax Cheddar Cheese Potato Chips", quantity: " 155.9 g", price: 266, mrp: 299, discount: null, image: "munchies/117.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_39", name: "Meiji Yan Yan Chocolate Dip Biscuit Sticks", quantity: " 50 g", price: 161, mrp: 169, discount: null, image: "munchies/118.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_40", name: "Kab's Jackpot Potato Stix Munchies", quantity: " 50 g", price: 65, mrp: null, discount: null, image: "munchies/119.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_41", name: "Lay's Stax Sour Cream & Onion Potato Chips", quantity: " 155.9 g", price: 350, mrp: null, discount: null, image: "munchies/120.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "munchies_42", name: "Kab's Jackpot Potato Stix Munchies (Aloo Chaat)", quantity: " 50 g", price: 65, mrp: null, discount: null, image: "munchies/106.png", inStock: true, deliveryTime: "13 minutes" }
];

const Hookah = [
  { productId: "hookah_1", name: "Flat Coconut Hookah Coal Cubes by Stash Pro", quantity: " 250 g", price: 180, mrp: null, discount: null, image: "hookah/101.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_2", name: "Paan Raas Herbal Hookah Flavor (Tobacco Free) by Soex", quantity: " 50 g", price: 100, mrp: null, discount: null, image: "hookah/102.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_3", name: "Coconut Hookah Coal Cubes by Stash Pro", quantity: " 250 g", price: 180, mrp: null, discount: null, image: "hookah/103.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_4", name: "Premium Magic Coal By Stash Pro", quantity: " 10 pieces", price: 80, mrp: null, discount: null, image: "hookah/104.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_5", name: "Mouth Filter Tips for Filters by Afzal", quantity: " 5 pieces", price: 38, mrp: 39, discount: null, image: "hookah/105.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_6", name: "Chief Commissioner Herbal Hookah Flavor (Tobacco Free) by Soex", quantity: " 50 g", price: 100, mrp: null, discount: null, image: "hookah/106.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_7", name: "Kiwi Herbal Hookah Flavor (Tobacco Free) by Soex", quantity: " 50 g", price: 100, mrp: null, discount: null, image: "hookah/107.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_8", name: "Ibiza – Beachy Vibes Hookah Flavor (Tobacco Free) by Hari Leaf", quantity: " 1 unit", price: 100, mrp: null, discount: null, image: "hookah/108.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_9", name: "Brain Freeze Up Herbal Hookah Flavor (Tobacco Free) by Soex", quantity: " 50 g", price: 100, mrp: null, discount: null, image: "hookah/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_10", name: "Hot Plate Heater Electric Coil Burner 500W by Cocoyaya", quantity: " 1 unit", price: 690, mrp: null, discount: null, image: "hookah/110.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_11", name: "Premium Silver Hookah Foil by Rhythm Imports", quantity: " 30 pieces", price: 100, mrp: null, discount: null, image: "hookah/111.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_12", name: "Silicon Hookah Chillum (Colour may Vary) by Smokey Lust", quantity: " 1 unit", price: 400, mrp: null, discount: null, image: "hookah/112.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_13", name: "Electric Charcoal Starter Hookah by Sheesha's Crown", quantity: " 1 unit", price: 699, mrp: null, discount: null, image: "hookah/113.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_14", name: "Metal Coal Hookah Cloud by Smokey Lust", quantity: " 1 unit", price: 350, mrp: null, discount: null, image: "hookah/114.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_15", name: "Coconut Hookah Coal by Cocoyaya", quantity: " 1 kg", price: 600, mrp: null, discount: null, image: "hookah/115.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_16", name: "Coconut Shell Hookah Coal by Cocoyaya", quantity: " 250 g", price: 150, mrp: null, discount: null, image: "hookah/116.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_17", name: "Double Apple Herbal Hookah Flavor (Tobacco Free) by Soex", quantity: " 50 g", price: 100, mrp: null, discount: null, image: "hookah/117.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_18", name: "Magic Coal by Cocoyaya", quantity: " 1 pack", price: 70, mrp: null, discount: null, image: "hookah/118.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_19", name: "Mouthpiece Hookah Pipe by Cocoyaya", quantity: " 1 pack (40 pieces)", price: 100, mrp: null, discount: null, image: "hookah/119.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_20", name: "Brain Froster Hookah Flavor (Tobacco Free) by Hari Leaf", quantity: " 1 unit", price: 100, mrp: null, discount: null, image: "hookah/120.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_21", name: "Silicon Hookah Pipe by Smokey Lust", quantity: " 1 unit", price: 600, mrp: null, discount: null, image: "hookah/121.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_22", name: "Bombay Paan Masala Herbal Hookah Flavor (Tobacco Free) by Soex", quantity: " 50 g", price: 100, mrp: null, discount: null, image: "hookah/122.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_23", name: "Flat Coconut Hookah Coal by Bongchie", quantity: " 1 pack (30 pieces)", price: 125, mrp: null, discount: null, image: "hookah/123.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_24", name: "Pre-Cut Hookah Foil by Cocoyaya", quantity: " 25 pieces", price: 70, mrp: null, discount: null, image: "hookah/124.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_25", name: "Tachi Bana Hookah by Cocoyaya", quantity: " 1 unit", price: 4890, mrp: null, discount: null, image: "hookah/125.jfif", inStock: true, deliveryTime: "20 minutes" },
  { productId: "hookah_26", name: "Instant Ignite Magic Coal by Bongchie", quantity: " 1 pack (10 pieces)", price: 80, mrp: null, discount: null, image: "hookah/126.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_27", name: "Organic Mud Hookah Chillum by Smokey Lust", quantity: " 1 unit", price: 75, mrp: null, discount: null, image: "hookah/127.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_28", name: "Premium Hookah Pipe by Smokey Lust", quantity: " 1 unit", price: 325, mrp: null, discount: null, image: "hookah/128.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_29", name: "Premium Hookah Charcoal Polo Magic Coal by Irfaz", quantity: " 1 pack (10 tablets)", price: 78, mrp: 79, discount: null, image: "hookah/129.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_30", name: "My Love – The Romantic Hookah Flavor (Tobacco Free) by Hari Leaf", quantity: " 1 unit", price: 100, mrp: null, discount: 8, image: "hookah/130.jfif", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_31", name: "Natural Coconut Hookah Charcoal Coal By Irfaz", quantity: " 30 pieces", price: 119, mrp: 130, discount: null, image: "hookah/131.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_32", name: "Iron Hookah Tong by Smokey Lust", quantity: " 1 unit", price: 100, mrp: null, discount: null, image: "hookah/132.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_33", name: "Coconut Hookah Coal by Bongchie", quantity: " 250 g", price: 125, mrp: null, discount: null, image: "hookah/133.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_34", name: "Petal Kiss – The Flamboyant Hookah Flavor (Tobacco Free) by Hari Leaf", quantity: " 1 unit", price: 100, mrp: null, discount: null, image: "hookah/134.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_35", name: "Indie Paan Hookah Flavor (Tobacco Free) by Hari Leaf", quantity: " 1 unit", price: 100, mrp: null, discount: 11, image: "hookah/135.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_36", name: "Ceramic Hookah Chillum by Smokey Lust", quantity: " 1 unit", price: 177, mrp: 200, discount: null, image: "hookah/136.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_37", name: "Hookah Tong by Cocoyaya", quantity: " 1 unit", price: 90, mrp: null, discount: null, image: "hookah/137.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_38", name: "Magic Water Hookah Flavor (Tobacco Free) by Hari Leaf", quantity: " 1 unit", price: 100, mrp: null, discount: null, image: "hookah/138.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "hookah_39", name: "Coal Holder Basket by Cocoyaya", quantity: " 1 unit", price: 900, mrp: null, discount: null, image: "hookah/139.png", inStock: true, deliveryTime: "13 minutes" }
];

const Mouthfresheners = [
  { productId: "mouthfresh_1", name: "Rajnigandha Silver Pearl Silver Coated Elaichi Mouth Freshener", quantity: " 5.75 g", price: 60, mrp: null, discount: null, image: "mouthfreshner/101.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_2", name: "Chandan Anardana Punch Mouth Freshener", quantity: " 170 g", price: 120, mrp: 140, discount: null, image: "mouthfreshner/103.jpg", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_3", name: "Spraymintt Icymint Mouth Freshener", quantity: " 15 g", price: 99, mrp: null, discount: null, image: "mouthfreshner/104.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_4", name: "Trident Original Flavour Gum (Sugar Free)", quantity: " 14 pieces", price: 150, mrp: null, discount: 14, image: "mouthfreshner/105.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_5", name: "Perfora Mouth Spray - Instant Fresh Breath (UM)", quantity: " 10 ml", price: 159, mrp: null, discount: null, image: "mouthfreshner/106.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_6", name: "Impact Sugar Free Mint Candy (Ice Mints)", quantity: " 14 g", price: 140, mrp: null, discount: null, image: "mouthfreshner/107.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_7", name: "Chandan Elaichi Saunf Mouth Freshener", quantity: " 100 g", price: 45, mrp: 50, discount: null, image: "mouthfreshner/108.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_8", name: "Pass Pass Sweet Magic Mix Mouth Freshener", quantity: " 105 g", price: 120, mrp: null, discount: null, image: "mouthfreshner/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_9", name: "Impact Sugar Free Mint Candy (Strong Mints)", quantity: " 14 g", price: 140, mrp: null, discount: null, image: "mouthfreshner/110.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_10", name: "Chandan Mint Saunf Mouth Freshener", quantity: " 100 g", price: 50, mrp: null, discount: 10, image: "mouthfreshner/111.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_11", name: "Trident Bubble Gum (Sugar Free)", quantity: " 14 pieces", price: 150, mrp: null, discount: null, image: "mouthfreshner/112.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_12", name: "Chandan Special Masala Mouth Freshener", quantity: " 100 g", price: 60, mrp: null, discount: 16, image: "mouthfreshner/113.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_13", name: "SURILI Aam Papad Mukhvas Mouth Freshener", quantity: " 200 g", price: 225, mrp: 270, discount: null, image: "mouthfreshner/114.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "mouthfresh_14", name: "Impact Sugar Free Mint Candy (Fresh Mints)", quantity: " 14 g", price: 140, mrp: null, discount: 5, image: "mouthfreshner/115.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_15", name: "Trident Tropical Twist Gum (Sugar Free)", quantity: " 14 pieces", price: 142, mrp: 150, discount: null, image: "mouthfreshner/116.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_16", name: "Impact Sugar Free Mint Candy (Strawberry)", quantity: " 14 g", price: 140, mrp: null, discount: null, image: "mouthfreshner/117.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_17", name: "Trident Watermelon Twist Gum (Sugar Free)", quantity: " 14 pieces", price: 150, mrp: null, discount: null, image: "mouthfreshner/118.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_18", name: "Tulsi Royal Khajoor Plus Flip-Top Can", quantity: " 30 g", price: 50, mrp: null, discount: null, image: "mouthfreshner/119.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_19", name: "Impact Black Currant Mint Candy - Sugar Free", quantity: " 14 g", price: 150, mrp: null, discount: null, image: "mouthfreshner/120.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_20", name: "Pass Pass Frutti Mix Mouth Freshener", quantity: " 105 g", price: 120, mrp: null, discount: null, image: "mouthfreshner/121.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_21", name: "Impact Sugar Free Mint Candy (Orange)", quantity: " 14 g", price: 150, mrp: null, discount: 39, image: "mouthfreshner/122.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_22", name: "Chandan Star 5 in 1 Mouth Freshener", quantity: " 200 g", price: 169, mrp: 280, discount: null, image: "mouthfreshner/123.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_23", name: "Chandan Jeera Goli Digestive Tablets", quantity: " 100 g", price: 45, mrp: null, discount: null, image: "mouthfreshner/124.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_24", name: "Impact Sugar Free Mint Candy (Peach)", quantity: " 14 g", price: 140, mrp: null, discount: null, image: "mouthfreshner/125.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_25", name: "Swad Anardana Goli", quantity: " 130 g", price: 198, mrp: 199, discount: 23, image: "mouthfreshner/126.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "mouthfresh_26", name: "Earthen Story Organic Gulkand", quantity: " 500 g", price: 499, mrp: 650, discount: null, image: "mouthfreshner/127.png", inStock: true, deliveryTime: "20 minutes" },
  { productId: "mouthfresh_27", name: "Trident Island Berry Lime Chewing Gum (Sugar Free)", quantity: " 14 pieces", price: 150, mrp: null, discount: null, image: "mouthfreshner/128.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_28", name: "Tulsi Royal Khajoor Plus", quantity: " 65 g (5 x 13 g)", price: 100, mrp: null, discount: null, image: "mouthfreshner/129.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_29", name: "Urban Platter Rose Petal Gulkand", quantity: " 300 g", price: 235, mrp: null, discount: 14, image: "mouthfreshner/130.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_30", name: "Chandan Regal Rose Mix Mouth Freshener", quantity: " 180 g", price: 129, mrp: 150, discount: 7, image: "mouthfreshner/131.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "mouthfresh_31", name: "Chandan Kashmiri Mouth Freshener", quantity: " 160 g", price: 139, mrp: 150, discount: null, image: "mouthfreshner/132.png", inStock: true, deliveryTime: "13 minutes" }
];

const ColdDrinks = [
  { productId: "colddrink_1", name: "Saras Unsalted Buttermilk", quantity: " 500 ml", price: 16, mrp: null, discount: 7, image: "colddrink/101.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_2", name: "Coca-Cola Soft Drink (750 ml)", quantity: " 750 ml", price: 37, mrp: 40, discount: null, image: "colddrink/103.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_3", name: "Bisleri Packaged Water (1 l)", quantity: " 1 l", price: 18, mrp: null, discount: null, image: "colddrink/104.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_4", name: "Amul Unsalted Buttermilk", quantity: " 440 ml", price: 15, mrp: null, discount: null, image: "colddrink/105.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_5", name: "Ice Cubes by Dras Ice", quantity: " 1 kg", price: 75, mrp: null, discount: null, image: "colddrink/106.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_6", name: "Amul Lactose Free Milk", quantity: " 250 ml", price: 25, mrp: null, discount: null, image: "colddrink/107.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_7", name: "Coca-Cola Diet Coke Soft Drink", quantity: " 300 ml", price: 40, mrp: null, discount: null, image: "colddrink/108.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_8", name: "Bisleri Packaged Water", quantity: " 5 l", price: 68, mrp: null, discount: null, image: "colddrink/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_9", name: "Aquafina Packaged Water", quantity: " 1 l", price: 18, mrp: null, discount: null, image: "colddrink/110.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_10", name: "Red Bull Energy Drink (250 ml)", quantity: " 250 ml", price: 125, mrp: null, discount: null, image: "colddrink/111.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_11", name: "Sprite Lime Flavored Soft Drink 750 ml", quantity: " 750 ml", price: 40, mrp: null, discount: null, image: "colddrink/112.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_12", name: "Kinley Strong Soda Water", quantity: " 750 ml", price: 18, mrp: null, discount: null, image: "colddrink/113.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_13", name: "7UP Nimbooz with Lemon Juice", quantity: " 350 ml", price: 23, mrp: null, discount: null, image: "colddrink/114.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_14", name: "Bisleri Soda Water", quantity: " 750 ml", price: 18, mrp: null, discount: null, image: "colddrink/115.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_15", name: "Bisleri Packaged Water - Pack of 24", quantity: " 24 x 250 ml", price: 132, mrp: null, discount: null, image: "colddrink/116.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_16", name: "Yakult Probiotic Drink", quantity: " 5 x 65 ml", price: 90, mrp: null, discount: null, image: "colddrink/117.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_17", name: "Coca-Cola Soft Drink (300 ml)", quantity: " 300 ml", price: 40, mrp: null, discount: 21, image: "colddrink/118.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_18", name: "Ice Cubes (Sparkling Supercubes) by Burrf", quantity: " 1 kg (16 pieces)", price: 78, mrp: 99, discount: null, image: "colddrink/119.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_19", name: "Appy Fizz Sparkling Drink (Apple Flavoured)", quantity: " 600 ml", price: 40, mrp: null, discount: null, image: "colddrink/120.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_20", name: "Amul Probiotic Tadka Salted Buttermilk", quantity: " 270 ml", price: 10, mrp: null, discount: null, image: "colddrink/121.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_21", name: "Red Bull Energy Drink (4 x 250 ml)", quantity: " 4 x 250 ml", price: 459, mrp: 480, discount: 15, image: "colddrink/122.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_22", name: "FruBon Masala Salted Buttermilk - Pack of 4", quantity: " 4 x 270 ml", price: 34, mrp: 40, discount: null, image: "colddrink/123.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_23", name: "Saras Salted Buttermilk", quantity: " 250 ml", price: 13, mrp: null, discount: null, image: "colddrink/124.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_24", name: "Mother Dairy Probiotic Tadka Salted Buttermilk", quantity: " 270 ml", price: 10, mrp: null, discount: null, image: "colddrink/125.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_25", name: "Monster Zero Sugar Ultra Energy Drink", quantity: " 350 ml", price: 125, mrp: null, discount: null, image: "colddrink/126.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_26", name: "Frooti Mango Drink", quantity: " 150 ml", price: 10, mrp: null, discount: null, image: "colddrink/127.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_27", name: "Coca-Cola Zero Sugar Soft Drink", quantity: " 300 ml", price: 40, mrp: null, discount: null, image: "colddrink/128.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_28", name: "Amul Masti Spiced Salted Buttermilk", quantity: " 200 ml", price: 15, mrp: null, discount: null, image: "colddrink/129.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_29", name: "Bisleri Vedica Mineral Water", quantity: " 1 l", price: 54, mrp: null, discount: 23, image: "colddrink/130.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "colddrink_30", name: "Real Activ Cranberry Juice", quantity: " 1 l", price: 129, mrp: 169, discount: null, image: "colddrink/131.png", inStock: true, deliveryTime: "13 minutes" }
];

const Candies = [
  { productId: "candy_1", name: "Chupa Chups Sour Bites Mixed Fruit Candy", quantity: " 61.6 g", price: 34, mrp: 35, discount: 17, image: "candies/101.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_2", name: "Parle Poppins Candy", quantity: " 100 g", price: 23, mrp: 28, discount: null, image: "candies/102.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_3", name: "Boomer Krunch Strawberry Chewing Gum", quantity: " 28.8 g", price: 48, mrp: 50, discount: null, image: "candies/103.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_4", name: "Orbit Mixed Fruit Flavour Chewing Gum (Sugar Free)", quantity: " 19.8 g", price: 45, mrp: null, discount: 6, image: "candies/104.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_5", name: "Alpenliebe Grande with Choco Delight Eclair", quantity: " 120 g", price: 47, mrp: 50, discount: 6, image: "candies/105.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_6", name: "Kopiko Cappuccino Candy - Family Pack", quantity: " 140 g", price: 44, mrp: 47, discount: null, image: "candies/106.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_7", name: "Pulse Golmol Imli Candy", quantity: " 175 g", price: 56, mrp: null, discount: 9, image: "candies/107.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_8", name: "Parle Kismi Assorted Candy - Pack of 2", quantity: " 2 x 245.5 g", price: 85, mrp: 94, discount: null, image: "candies/108.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_9", name: "GO DESi Tangy Imli Desi Popz Lollipop Candy", quantity: " 8 pieces", price: 50, mrp: null, discount: 6, image: "candies/109.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_10", name: "Happydent White Spearmint Sugar Free Chewing Gum", quantity: " 24.2 g", price: 47, mrp: 50, discount: null, image: "candies/110.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_11", name: "Alpenliebe Pop Assorted Flavours Lollipop (with Toy Inside)", quantity: " 8 x 8 g", price: 48, mrp: 50, discount: null, image: "candies/111.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_12", name: "Wrigley's Doublemint Peppermint Chewy Mint Candies", quantity: " 27.3 g", price: 45, mrp: null, discount: null, image: "candies/112.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_13", name: "Alpenliebe Juzt Jelly - Strawberry Flavour Jelly Candy", quantity: " 140 g", price: 53, mrp: 55, discount: null, image: "candies/113.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_14", name: "Poko Loko Strawberry Sour Tape Candy", quantity: " 25 g", price: 50, mrp: null, discount: 8, image: "candies/114.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_15", name: "Parle Melody Max Chocolaty Candy", quantity: " 271.4 g", price: 81, mrp: 89, discount: null, image: "candies/115.jpg", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_16", name: "Chupa Chups Strawberry And Watermelon Soft Candy", quantity: " 80 g", price: 48, mrp: 50, discount: null, image: "candies/116.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_17", name: "Sour Punk Cola Flavour Stick Candy", quantity: " 40 g", price: 40, mrp: null, discount: null, image: "candies/117.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_18", name: "Fruittella Strawberry Flavour Chewy Toffee", quantity: " 45 g", price: 34, mrp: 35, discount: null, image: "candies/118.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_19", name: "Haribo Chamallows Marshmallow (Pink & White)", quantity: " 140 g", price: 250, mrp: null, discount: 10, image: "candies/119.jpg", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_20", name: "Chandan Aam Papad", quantity: " 200 g", price: 162, mrp: 180, discount: null, image: "candies/120.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_21", name: "Nestle Polo Mint Candies", quantity: " 50 x 1.5 g", price: 50, mrp: null, discount: 17, image: "candies/121.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_22", name: "Parle Rol a Cola Candy", quantity: " 100 g", price: 23, mrp: 28, discount: null, image: "candies/122.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_23", name: "Trident Original Flavour Gum (Sugar Free)", quantity: " 14 pieces", price: 150, mrp: null, discount: 12, image: "candies/123.jpg", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_24", name: "Impact Strike Watermelon Chewing Gum", quantity: " 29 g", price: 88, mrp: 100, discount: 6, image: "candies/124.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_25", name: "Happydent Sugar Free Wave Fruit Flavour Chewing Gum", quantity: " 28.9 g", price: 47, mrp: 50, discount: null, image: "candies/125.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_26", name: "Paper Boat Aam Papad Fruit Bar", quantity: " 90 g", price: 84, mrp: 85, discount: null, image: "candies/126.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_27", name: "Mentos Rainbow Chewy Candy (Assorted) 40 Pcs", quantity: " 108 g", price: 48, mrp: 50, discount: null, image: "candies/127.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_28", name: "Impact Sugar Free Mint Candy (Ice Mints)", quantity: " 14 g", price: 140, mrp: null, discount: null, image: "candies/128.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_29", name: "Pulse Litchi with Tangy Twist Candy", quantity: " 190 g", price: 60, mrp: null, discount: 25, image: "candies/129.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_30", name: "Parle Orange Bite Bigger - Orangee Jhatkaa Candy - Pack of 2", quantity: " 2 x 214.5 g", price: 85, mrp: 114, discount: null, image: "candies/130.png", inStock: true, deliveryTime: "13 minutes" },
  { productId: "candy_31", name: "Orbit Spearmint Flavour Sugar Free Chewing Gum", quantity: " 19.8 g", price: 45, mrp: null, discount: null, image: "candies/104.png", inStock: true, deliveryTime: "13 minutes" }
];

export { Dairy, Tobacco, Munchies, Hookah, Mouthfresheners, ColdDrinks, Candies };
